### ISSUE TITLE
Unable to build: Error: no native function or rule 'new_http_archive'

### ISSUE THREAD

**Issue by stolj** [smyte/smyte-db#6]
Thanks a lot for your code contributions. We're trying to evaluate the 'ratelimit' server, but are unable to build. We're getting the following:

$ bazel clean && bazel build ratelimit
Starting local Bazel server and connecting to it...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
ERROR: Traceback (most recent call last):
	File "/home/tolj/src/ratelimit/smyte-db/WORKSPACE", line 4, column 16, in <toplevel>
		smyte_workspace("")
	File "/home/tolj/src/ratelimit/smyte-db/third_party/workspace.bzl", line 6, column 11, in smyte_workspace
		native.new_http_archive(
Error: no native function or rule 'new_http_archive'
Available attributes: aar_import, action_listener, alias, android_binary, android_device, android_device_script_fixture, android_host_service_fixture, android_instrumentation_test, android_library, android_local_test, android_ndk_repository, android_sdk, android_sdk_repository, android_tools_defaults_jar, apple_binary, apple_cc_toolchain, apple_static_library, available_xcodes, bazel_version, bind, cc_binary, cc_host_toolchain_alias, cc_import, cc_libc_top_alias, cc_library, cc_proto_library, cc_test, cc_toolchain, cc_toolchain_alias, cc_toolchain_suite, config_feature_flag, config_setting, constraint_setting, constraint_value, environment, existing_rule, existing_rules, exports_files, extra_action, fdo_prefetch_hints, fdo_profile, filegroup, genquery, genrule, glob, j2objc_library, java_binary, java_import, java_library, java_lite_proto_library, java_package_configuration, java_plugin, java_proto_library, java_runtime, java_runtime_alias, java_test, java_toolchain, java_toolchain_alias, label_flag, label_setting, local_config_platform, local_repository, new_local_repository, ninja_build, ninja_graph, objc_import, objc_library, package_group, package_name, platform, proto_lang_toolchain, proto_library, py_binary, py_library, py_runtime, py_test, register_execution_platforms, register_toolchains, repository_name, sh_binary, sh_library, sh_test, test_suite, toolchain, toolchain_type, xcode_config, xcode_config_alias, xcode_version
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 3.628s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

on ubuntu-18 and

$ bazel version
Build label: 3.5.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Sep 2 20:11:46 2020 (1599077506)
Build timestamp: 1599077506
Build timestamp as int: 1599077506

It seems that the 'new_http_archive' has been deprecated for some time by bazel. Since we're no experts in bazel, is there any chance you can update the build environment to fit the latest bazel release?

Thanks.
Stipe

**Comment by robertmircea** [comment]
I have the same issue.
